/*
 * SonarSource Go
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.go.checks;

import java.util.ArrayDeque;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BiConsumer;
import org.junit.jupiter.api.Test;
import org.sonar.api.batch.fs.InputFile;
import org.sonar.go.testing.GoVerifier;
import org.sonar.plugins.go.api.Tree;
import org.sonar.plugins.go.api.VariableDeclarationTree;
import org.sonar.plugins.go.api.checks.CheckContext;
import org.sonar.plugins.go.api.checks.InitContext;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class VariableAndParameterNameCheckTest {

  private final VariableAndParameterNameCheck check = new VariableAndParameterNameCheck();

  @Test
  void shouldRaiseOnVariableAndParameterNamesWithDefaultRegex() {
    GoVerifier.verify("VariableAndParameterNameCheck/VariableAndParameterNameCheckDefault.go", check);
  }

  @Test
  void shouldRaiseOnVariableAndParameterNamesWithChangedRegex() {
    var checkWithChangedRegex = new VariableAndParameterNameCheck();
    checkWithChangedRegex.format = "^([A-Z]+)$";
    GoVerifier.verify("VariableAndParameterNameCheck/VariableAndParameterNameCheckChangedRegex.go", checkWithChangedRegex);
  }

  @Test
  void shouldNotRaiseOnTemplGeneratedFile() {
    GoVerifier.verifyNoIssue("VariableAndParameterNameCheck/VariableAndParameterNameCheck_templ.go", check);
  }

  /**
   * Verifies that generated source markers suppress local-variable and parameter naming issues.
   */
  @Test
  void shouldNotRaiseOnStandardGeneratedFile() {
    GoVerifier.verifyNoIssue("VariableAndParameterNameCheck/VariableAndParameterNameCheckGenerated.go", check);
  }

  /**
   * Verifies that files sharing a filename keep distinct generated-source cache entries.
   */
  @Test
  void shouldCacheGeneratedFileStatusByInputFileKey() {
    var generatedContext = mock(CheckContext.class);
    var regularContext = mock(CheckContext.class);
    var generatedInputFile = mock(InputFile.class);
    var regularInputFile = mock(InputFile.class);
    when(generatedContext.filename()).thenReturn("main.go");
    when(generatedContext.inputFile()).thenReturn(generatedInputFile);
    when(generatedInputFile.key()).thenReturn("project:generated/main.go");
    when(generatedContext.fileContent()).thenReturn("// Code generated by mockery. DO NOT EDIT.\npackage generated");
    when(regularContext.filename()).thenReturn("main.go");
    when(regularContext.inputFile()).thenReturn(regularInputFile);
    when(regularInputFile.key()).thenReturn("project:regular/main.go");
    when(regularContext.fileContent()).thenReturn("package regular");

    assertThat(check.isGeneratedFile(generatedContext)).isTrue();
    assertThat(check.isGeneratedFile(generatedContext)).isTrue();
    assertThat(check.isGeneratedFile(regularContext)).isFalse();

    verify(generatedContext, times(1)).fileContent();
  }

  @Test
  void shouldNotReadContentForPackageVariables() {
    var variableVisitor = new AtomicReference<BiConsumer<CheckContext, VariableDeclarationTree>>();
    check.initialize(new InitContext() {
      @Override
      @SuppressWarnings("unchecked")
      public <T extends Tree> void register(Class<T> type, BiConsumer<CheckContext, T> visitor) {
        if (type == VariableDeclarationTree.class) {
          variableVisitor.set((BiConsumer<CheckContext, VariableDeclarationTree>) visitor);
        }
      }

      @Override
      public void registerOnLeave(BiConsumer<CheckContext, Tree> visitor) {
        // This check does not register leave visitors.
      }
    });
    var context = mock(CheckContext.class);
    when(context.ancestors()).thenReturn(new ArrayDeque<>());

    variableVisitor.get().accept(context, mock(VariableDeclarationTree.class));

    verify(context, never()).fileContent();
  }

}
