/*
 * SonarSource Go
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * You can redistribute and/or modify this program under the terms of
 * the Sonar Source-Available License Version 1, as published by SonarSource Sàrl.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the Sonar Source-Available License for more details.
 *
 * You should have received a copy of the Sonar Source-Available License
 * along with this program; if not, see https://sonarsource.com/license/ssal/
 */
package org.sonar.plugins.go.api.checks;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class GeneratedCodeDetectorTest {

  /**
   * Verifies that leading standard markers identify generated source files.
   */
  @Test
  void shouldRecognizeLeadingGeneratedCodeMarker() {
    assertThat(GeneratedCodeDetector.isGenerated("// Copyright\n\n// Code generated by mockery. DO NOT EDIT.\npackage generated"))
      .isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("/* Copyright */\n// Code generated from template. DO NOT EDIT.\npackage generated"))
      .isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("// Code generated  DO NOT EDIT.\npackage generated")).isTrue();
  }

  /**
   * Verifies that non-standard or misplaced markers do not identify generated source files.
   */
  @Test
  void shouldRejectUnmarkedAndMisplacedGeneratedCodeMarkers() {
    assertThat(GeneratedCodeDetector.isGenerated("package generated\nvar value int")).isFalse();
    assertThat(GeneratedCodeDetector.isGenerated("package generated\n// Code generated by mockery. DO NOT EDIT.")).isFalse();
    assertThat(GeneratedCodeDetector.isGenerated("// Code generated DO NOT EDIT.\npackage generated")).isFalse();
    assertThat(GeneratedCodeDetector.isGenerated("// Code generated by mockery. DO NOT EDIT\npackage generated")).isFalse();
  }

  /**
   * Verifies compatibility with edge cases recognized by Go's ast.IsGenerated.
   */
  @Test
  void shouldRecognizeGoAstGeneratedEdgeCases() {
    assertThat(GeneratedCodeDetector.isGenerated("/*\n// Code generated by mockery. DO NOT EDIT.\n*/\npackage generated")).isTrue();
    assertThat(GeneratedCodeDetector.isGenerated(" // Code generated by mockery. DO NOT EDIT.\npackage generated")).isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("/* Copyright */ // Code generated by mockery. DO NOT EDIT.\npackage generated"))
      .isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("/* Copyright\n*/ // Code generated by mockery. DO NOT EDIT.\npackage generated"))
      .isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("/* Copyright */ /* License */ // Code generated by mockery. DO NOT EDIT.\npackage generated"))
      .isTrue();
  }

  /**
   * Verifies that marker detection follows Go's line separator handling.
   */
  @Test
  void shouldUseGoLineSeparatorSemantics() {
    assertThat(GeneratedCodeDetector.isGenerated("// Code generated by\fmockery. DO NOT EDIT.\npackage generated")).isTrue();
    assertThat(GeneratedCodeDetector.isGenerated("// Code generated by mockery.\r DO NOT EDIT.\npackage generated")).isTrue();
  }
}
